# Generated by Django 5.1 on 2024-09-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("english_name", models.CharField(max_length=100, null=True)),
                ("directors", models.CharField(max_length=100, null=True)),
                ("writer", models.CharField(max_length=100, null=True)),
                ("actors", models.CharField(max_length=100, null=True)),
                ("rate", models.CharField(max_length=100, null=True)),
                ("style1", models.CharField(max_length=100, null=True)),
                ("style2", models.CharField(max_length=100, null=True)),
                ("style3", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("language", models.CharField(max_length=100, null=True)),
                ("date", models.CharField(max_length=100, null=True)),
                ("duration", models.CharField(max_length=100, null=True)),
                ("introduction", models.CharField(max_length=1000, null=True)),
                ("dataID", models.CharField(max_length=100, null=True)),
                ("url", models.CharField(max_length=100, null=True)),
                ("pic", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movies_recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("english_name", models.CharField(max_length=100, null=True)),
                ("directors", models.CharField(max_length=100, null=True)),
                ("writer", models.CharField(max_length=100, null=True)),
                ("actors", models.CharField(max_length=100, null=True)),
                ("rate", models.CharField(max_length=100, null=True)),
                ("style1", models.CharField(max_length=100, null=True)),
                ("style2", models.CharField(max_length=100, null=True)),
                ("style3", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("language", models.CharField(max_length=100, null=True)),
                ("date", models.CharField(max_length=100, null=True)),
                ("duration", models.CharField(max_length=100, null=True)),
                ("introduction", models.CharField(max_length=1000, null=True)),
                ("dataID", models.CharField(max_length=100, null=True)),
                ("url", models.CharField(max_length=100, null=True)),
                ("pic", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True)),
                ("movieID", models.CharField(max_length=100, null=True)),
                ("rating", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("PassWord", models.CharField(max_length=100)),
                ("xuanyi", models.BooleanField(default=False)),
                ("fanzui", models.BooleanField(default=False)),
                ("kehuan", models.BooleanField(default=False)),
                ("tongxing", models.BooleanField(default=False)),
                ("maoxian", models.BooleanField(default=False)),
                ("kongbu", models.BooleanField(default=False)),
                ("juqing", models.BooleanField(default=False)),
                ("aiqing", models.BooleanField(default=False)),
                ("zainan", models.BooleanField(default=False)),
                ("xiju", models.BooleanField(default=False)),
                ("donghua", models.BooleanField(default=False)),
                ("qingse", models.BooleanField(default=False)),
            ],
        ),
    ]
