# Generated by Django 5.1 on 2024-09-05 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webtests", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="movieID",
            new_name="dataID",
        ),
    ]
