# Generated by Django 5.1.1 on 2024-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtests', '0002_rename_movieid_rating_dataid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='dongzuo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='duanpian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='ertong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='gewu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='guzhuang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='heise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='jiating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='jilupian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='jingsong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='lishi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='qihuan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='tuokouxiu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='wuxia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='xibu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='xiqu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='yinyue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='yundong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='zhanzheng',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='zhenrenxiu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='zhuanji',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
