from django.db import models

class User_info(models.Model):
    username = models.CharField(max_length=100)
    PassWord = models.CharField(max_length=100)
    xuanyi = models.BooleanField(default=False)
    fanzui = models.BooleanField(default=False)
    kehuan = models.BooleanField(default=False)
    tongxing = models.BooleanField(default=False)
    maoxian = models.BooleanField(default=False)
    kongbu = models.BooleanField(default=False)
    juqing = models.BooleanField(default=False)
    aiqing = models.BooleanField(default=False)
    zainan = models.BooleanField(default=False)
    xiju = models.BooleanField(default=False)
    donghua = models.BooleanField(default=False)
    qingse = models.BooleanField(default=False)

    jingsong = models.BooleanField(default=False)
    jilupian = models.BooleanField(default=False)
    dongzuo = models.BooleanField(default=False)
    qihuan = models.BooleanField(default=False)
    jiating = models.BooleanField(default=False)
    yundong = models.BooleanField(default=False)
    zhenrenxiu = models.BooleanField(default=False)
    wuxia = models.BooleanField(default=False)
    guzhuang = models.BooleanField(default=False)
    lishi = models.BooleanField(default=False)
    zhanzheng = models.BooleanField(default=False)
    tuokouxiu = models.BooleanField(default=False)
    yinyue = models.BooleanField(default=False)
    ertong = models.BooleanField(default=False)
    zhuanji = models.BooleanField(default=False)
    xibu = models.BooleanField(default=False)
    gewu = models.BooleanField(default=False)
    duanpian = models.BooleanField(default=False)
    xiqu = models.BooleanField(default=False)
    heise = models.BooleanField(default=False)


class Movies(models.Model):
    name = models.CharField(max_length=100, null=True)
    english_name = models.CharField(max_length=100, null=True)
    directors = models.CharField(max_length=100, null=True)
    writer = models.CharField(max_length=100, null=True)
    actors = models.CharField(max_length=100, null=True)
    rate = models.CharField(max_length=100, null=True)
    style1 = models.CharField(max_length=100, null=True)
    style2 = models.CharField(max_length=100, null=True)
    style3 = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    language = models.CharField(max_length=100, null=True)
    date = models.CharField(max_length=100, null=True)
    duration = models.CharField(max_length=100, null=True)
    introduction = models.CharField(max_length=1000, null=True)
    dataID = models.CharField(max_length=100, null=True)
    url = models.CharField(max_length=100, null=True)
    pic = models.CharField(max_length=100, null=True)


class Movies_recommend(models.Model):
    name = models.CharField(max_length=100, null=True)
    english_name = models.CharField(max_length=100, null=True)
    directors = models.CharField(max_length=100, null=True)
    writer = models.CharField(max_length=100, null=True)
    actors = models.CharField(max_length=100, null=True)
    rate = models.CharField(max_length=100, null=True)
    style1 = models.CharField(max_length=100, null=True)
    style2 = models.CharField(max_length=100, null=True)
    style3 = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    language = models.CharField(max_length=100, null=True)
    date = models.CharField(max_length=100, null=True)
    duration = models.CharField(max_length=100, null=True)
    introduction = models.CharField(max_length=1000, null=True)
    dataID = models.CharField(max_length=100, null=True)
    url = models.CharField(max_length=100, null=True)
    pic = models.CharField(max_length=100, null=True)

class Rating(models.Model):
    username = models.CharField(max_length=100, null=True)
    dataID = models.CharField(max_length=100, null=True)
    rating = models.IntegerField()
